version: 1.2
workflows:
   - name: "Cut-and-Run"
     subclass: WDL
     primaryDescriptorPath: /cut-and-run.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - main
             - v2
         tags:
             - /.*/
   - name: "Cut-and-Run-qc"
     subclass: WDL
     primaryDescriptorPath: /workflows/qc-cut-n-run.wdl
     filters:  # Only develop or master branches and localAligner/** tags
         branches:
             - v2
             - main
         tags:
             - /.*/